theme: minima
title: Your Playmate Sock Dolls, LLC
permalink: pretty
baseurl: "/your-playmate-sock-dolls"
description: Bringing comfort to seriously ill children.
markdown: kramdown

navigation:
  - title: "Home"
    url: /
  - title: "About Us"
    url: /about
  - title: "Contact Us"
    url: /contact
  - title: "Order Checkout"
    url: /checkout
  - title: "Login"
    url: /login
  - title: "Register"
    url: /register
